console.log('')
console.log('============================')
console.log('  _                      _ ')
console.log(' | |                    | |')
console.log(' | |__   ___  __ _  __ _| |')
console.log(' | \'_ \\ / _ \\/ _` |/ _` | |')
console.log(' | |_) |  __/ (_| | (_| | |')
console.log(' |_.__/ \\___|\\__,_|\\__, |_|')
console.log('                    __/ |  ')
console.log('                   |___/   ')
console.log('============================')
console.log('')